#!/bin/bash
echo "<d83c> LaTeX 完整版字体库 - 安装情况报告"
echo "=============================================="
echo ""

echo "<d83d> 字体统计："
echo "  总字体数量: $(fc-list | wc -l)"
echo "  中文字体数量: $(fc-list :lang=zh | wc -l)"
echo "  英文字体数量: $(fc-list :lang=en | wc -l)"
echo ""

echo "<d83d> Google Fonts 手写体系列："
cd /usr/share/fonts/truetype/google-fonts 2>/dev/null || echo "  目录不存在"
ls -1 *.ttf 2>/dev/null | while read font; do
    echo "  ✅ $font"
done || echo "  ❌ 未找到 Google Fonts"
echo ""

echo "<d83c> 站酷字体系列："
echo "  站酷快乐体: $(fc-list | grep -i 'kuaile\|快乐' | wc -l) 个"
echo "  站酷小微体: $(fc-list | grep -i 'xiaowei\|小微' | wc -l) 个"
echo "  站酷青科黄油体: $(fc-list | grep -i 'qingke\|huangyou\|青科\|黄油' | wc -l) 个"
echo ""

echo "<d83c> 阿里巴巴普惠体系列："
echo "  普惠体数量: $(fc-list | grep -i 'alibaba\|puhuiti\|普惠' | wc -l) 个"
echo ""

echo "✍️ 创意和手写字体："
echo "  得意黑: $(fc-list | grep -i 'smiley\|得意' | wc -l) 个"
echo "  霞鹜文楷: $(fc-list | grep -i 'lxgw\|wenkai\|文楷' | wc -l) 个"
echo "  江西拙楷: $(fc-list | grep -i 'jiangxi\|zhuokai\|拙楷' | wc -l) 个"
echo "  仓耳今楷: $(fc-list | grep -i 'tsanger\|今楷' | wc -l) 个"
echo ""

echo "<d83c> 传统中文字体："
echo "  文泉驿字体: $(fc-list | grep -i 'wenquanyi\|文泉驿' | wc -l) 个"
echo "  思源字体: $(fc-list | grep -i 'noto\|source.*han' | wc -l) 个"
echo "  方正字体: $(fc-list | grep -i 'arphic\|方正' | wc -l) 个"
echo ""

echo "<d83d> 字体目录详情："
echo "  Google Fonts: $(ls /usr/share/fonts/truetype/google-fonts/*.ttf 2>/dev/null | wc -l) 个文件"
echo "  站酷字体: $(ls /usr/share/fonts/truetype/zcool/*.ttf 2>/dev/null | wc -l) 个文件"
echo "  阿里巴巴字体: $(find /usr/share/fonts/truetype/alibaba -name "*.ttf" 2>/dev/null | wc -l) 个文件"
echo "  创意字体: $(ls /usr/share/fonts/truetype/creative/*.ttf 2>/dev/null | wc -l) 个文件"
echo "  手写字体: $(ls /usr/share/fonts/truetype/handwriting/*.ttf 2>/dev/null | wc -l) 个文件"
echo ""

echo "<d83d> LaTeX 使用示例："
echo "  \\usepackage{xeCJK}"
echo "  \\setCJKmainfont{Noto Sans CJK SC}           % 思源黑体"
echo "  \\setCJKmainfont{LXGWWenKai-Regular}         % 霞鹜文楷"
echo "  \\setCJKmainfont{ZcoolKuaiLe-Regular}        % 站酷快乐体"
echo "  \\newfontfamily\\alibaba{Alibaba Sans}        % 阿里巴巴普惠体"
echo "  \\newfontfamily\\handwrite{Patrick Hand}      % Google手写体"
echo ""

echo "<d83d> 使用提示："
echo "  - 中文字体建议使用 XeLaTeX 编译"
echo "  - 英文手写体可与中文字体混合使用"
echo "  - 运行 'fc-list :lang=zh' 查看所有中文字体"
echo "  - 运行 'fc-list | grep -i handwrite' 查看手写体"
echo ""
echo "=============================================="
