FROM dsw-registry.cn-wulanchabu.cr.^Ciyuncs.com/pai/pai-megatron-patch:25.02

RUN pip install \
    filetype==1.2.0 \
    bitstring==4.3.1 \
    ebmlite==3.3.1 \
    av==14.3.0 \
    webdataset==0.2.111 \
    opencv-python==4.11.0.86 \
    pillow==11.1.0
